# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-nlp-talk',
                'doc_host': 'https://khankanz.github.io',
                'git_url': 'https://github.com/khankanz/nbdev-nlp-talk',
                'lib_path': 'nbdev_nlp_talk'},
  'syms': {'nbdev_nlp_talk.core': {'nbdev_nlp_talk.core.foo': ('core.html#foo', 'nbdev_nlp_talk/core.py')}}}
