# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_llm_intro.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_llm_intro.ipynb 13
from IPython.display import display,Image

# %% ../nbs/00_llm_intro.ipynb 14
display(Image('assets/tmcrs.png'))

# %% ../nbs/00_llm_intro.ipynb 15
display(Image('assets/mry.png'))

# %% ../nbs/00_llm_intro.ipynb 23
display(Image('assets/leaderboard.png'))
