# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_llm_intro.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_llm_intro.ipynb 24
from IPython.display import display,Image

# %% ../nbs/00_llm_intro.ipynb 25
display(Image('assets/tmcrs.png'))

# %% ../nbs/00_llm_intro.ipynb 26
display(Image('assets/mry.png'))
