# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_tokenization.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_tokenization.ipynb 2
from nltk.tokenize import sent_tokenize

# %% ../nbs/01_tokenization.ipynb 6
from IPython.display import display,Image

# %% ../nbs/01_tokenization.ipynb 7
display(Image('assets/brst-tokenizer.png'))

# %% ../nbs/01_tokenization.ipynb 11
display(Image('assets/gpt2.png'))

# %% ../nbs/01_tokenization.ipynb 12
display(Image('assets/ck100.png'))
